classDiagram
    %% new class diagramme made at the start of iter 2
    MainMenu --> Main : Start game    
    Main -->  Player : initialise
    
    Main --> Hand : initialise
    

    note for MainMenu "Start the programme"

    Manager <-- Build
    MainMenu --> BoardBuilder
    BoardBuilder --> board
    Player --> Manager
    Player "1" *-- "1" Hand
    Manager <-- Dice
    tile --* board

    Manager <-- tile

    Manager <-- trade
    trade <-- PlayerTrade
    trade <-- BankTrade

    sea  <|-- tile
    sand <|-- tile
    resource <|-- tile
    
    PassivePayout --> tile
    PassivePayout --> Player

    class BankTrade {

    }

    class PassivePayout {

    }

    class PlayerTrade {

    }

    class Main {
        + Players PlayerList
        + GameStatus state
        + construct()
        +playerOrder()
    }

    class BoardBuilder {
        +activateBoard()

    }

    class MainMenu {
        +activateGame()

    }
    class Hand {

    }

    class Manager {
        -acceptAction()
    }

    class Dice{
      +Roll()
      -makeSum()

    }
    class CostTable {
        %% This is actually 2 classes.
        +displayTable()
    }

    class board{
        +displayBoard()
    }
    class resource{
    }

    class tile{

    }
    class sea{

    }
    class sand{

    }
    class Build{

    }

    class Player{
      +bool State
      -displayHand()
    }
