sequenceDiagram
Constructor->>GameStatus: Game status?
GameStatus-->>Constructor: Game status is x
Constructor ->> Constructor: set current player given Game status
Constructor->> Player: Want to trade? 
Player -->> Constructor: Yes I want to trade with player "x"
Constructor->> Player: Want to build? 
Player -->> Constructor: Yes I want to build 'x'
Constructor ->> Manager: Can they build?
Manager -->> Constructor: Yes they can!
Constructor->> Build: Build something
Constructor->> Player: where do you can to build?
Player -->> Constructor: I want to build here 
Constructor ->> Manager: Can they build here?
Manager ->> Board: Is this spot this free?
Board -->> Manager: Yes it is!
Manager -->> Constructor: You can build here, continue?
Constructor ->> Player: Confirm build
Player --> Constructor: yes I want to build
Constructor --> Board: update field
Constructor ->> Constructor: set next player
