---
title: Trading diagramme -- when any party declines; the trade is re started.
---
sequenceDiagram
    Player (active) -->> Manager: request a trade
    Manager -->> Player (active): accept
    Player (active) -->> Trade: I want trade X
    Trade -->> Player (inactive): Show offer X
    Player (inactive) -->> Trade: accept or decline
    Trade -->> Trade: Check offer X
    Trade -->> Player (active): Offer show offer X
    Player (active) -->> Trade: Accept/Decline
    Trade -->> Player (inactive): Accept trade
    Trade -->> Player (inactive): Execute trade
    Trade -->> Player (active): Execute trade
